# Generated by Django 6.0.4 on 2026-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_ativo_produto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cadastrado_manual',
            field=models.BooleanField(default=False, verbose_name='cadastrado manual'),
        ),
        migrations.AddField(
            model_name='produto',
            name='incompleto',
            field=models.BooleanField(default=True, verbose_name='incompleto'),
        ),
    ]
