# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models


def _popular_grupos_agregados(apps, schema_editor):
    Produto = apps.get_model('produtos', 'Produto')
    GrupoAgregado = apps.get_model('produtos', 'GrupoAgregado')

    for produto in Produto.objects.all().iterator():
        setor = (produto.setor or '').strip().upper()
        if not setor:
            continue
        grupo, _ = GrupoAgregado.objects.get_or_create(nome=setor)
        produto.grupos_agregados.add(grupo)


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_codigo_produto_embalagem_produto_setor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'grupo agregado',
                'verbose_name_plural': 'grupos agregados',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['nome'], name='grupo_agregado_nome_idx')],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='grupos_agregados',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='produtos.grupoagregado', verbose_name='grupos agregados'),
        ),
        migrations.RunPython(_popular_grupos_agregados, migrations.RunPython.noop),
    ]
