services:
  - type: web
    name: wms
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py create_render_superuser && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: DATABASE_URL
        value: postgresql://postgres.qvsfsccdvuujqxceogfz:JOELRAFA010103@aws-1-us-east-1.pooler.supabase.com:6543/postgres
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@wms.local
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
      - key: LOG_LEVEL
        value: INFO