# Generated by Django 6.0.4 on 2026-04-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('FILTRO', 'Filtro')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_SEPARACAO', 'Em separacao'), ('SEPARADO', 'Separado'), ('PARCIAL', 'Parcial'), ('CANCELADA', 'Cancelada')], db_index=True, max_length=20, verbose_name='status')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='rotas.rota', verbose_name='rota')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TarefaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade total')),
                ('quantidade_separada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantidade separada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_tarefa', to='produtos.produto', verbose_name='produto')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tarefas.tarefa', verbose_name='tarefa')),
            ],
            options={
                'verbose_name': 'item da tarefa',
                'verbose_name_plural': 'itens da tarefa',
                'ordering': ('tarefa_id', 'produto_id'),
            },
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['tipo', 'status'], name='tarefa_tipo_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['rota', 'status'], name='tarefa_rota_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefaitem',
            index=models.Index(fields=['tarefa', 'produto'], name='tarefa_item_tarefa_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefaitem',
            index=models.Index(fields=['produto'], name='tarefa_item_produto_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarefaitem',
            constraint=models.UniqueConstraint(fields=('tarefa', 'produto'), name='tarefa_item_unique_produto'),
        ),
        migrations.AddConstraint(
            model_name='tarefaitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_separada__gte', 0), ('quantidade_total__gt', 0)), name='tarefa_item_quantidades_validas_chk'),
        ),
    ]
