# Generated by Django 6.0.4 on 2026-04-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf', '0002_remove_notafiscal_nf_chave_idx'),
        ('rotas', '0001_initial'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='nf.notafiscal', verbose_name='nota fiscal'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['nf', 'status'], name='tarefa_nf_status_idx'),
        ),
    ]
