# Generated by Django 6.0.4 on 2026-04-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_tarefa_nf_tarefa_tarefa_nf_status_idx'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='setor',
            field=models.CharField(choices=[('LUBRIFICANTE', 'Lubrificante'), ('AGREGADO', 'Agregado'), ('FILTROS', 'Filtros'), ('NAO_ENCONTRADO', 'Nao encontrado')], default='NAO_ENCONTRADO', max_length=20, verbose_name='setor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.CharField(choices=[('ROTA', 'Rota'), ('FILTRO', 'Filtro')], max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluido'), ('FECHADO_COM_RESTRICAO', 'Fechado com restricao')], db_index=True, max_length=30, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['setor', 'status'], name='tarefa_setor_status_idx'),
        ),
    ]