# Generated by Django 6.0.4 on 2026-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_remove_tarefaitem_tarefa_item_unique_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluido'), ('FECHADO_COM_RESTRICAO', 'Fechado com restricao'), ('LIBERADO_COM_RESTRICAO', 'Liberado com restricao'), ('CONCLUIDO_COM_RESTRICAO', 'Concluido com restricao')], db_index=True, max_length=30, verbose_name='status'),
        ),
    ]
