# Generated by Django 6.0.4 on 2026-04-29

from django.db import migrations, models
import django.db.models.deletion


def _vincular_grupo_agregado_nos_itens(apps, schema_editor):
    TarefaItem = apps.get_model('tarefas', 'TarefaItem')
    GrupoAgregado = apps.get_model('produtos', 'GrupoAgregado')

    grupos_cache = {g.nome: g for g in GrupoAgregado.objects.all()}

    for item in TarefaItem.objects.select_related('produto').all().iterator():
        if item.grupo_agregado_id:
            continue
        setor = (getattr(item.produto, 'setor', None) or '').strip().upper()
        if not setor:
            continue
        grupo = grupos_cache.get(setor)
        if grupo is None:
            grupo = GrupoAgregado.objects.create(nome=setor)
            grupos_cache[setor] = grupo
        item.grupo_agregado_id = grupo.id
        item.save(update_fields=['grupo_agregado'])


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_grupoagregado_produto_grupos_agregados'),
        ('tarefas', '0010_tarefa_usuario_execucao_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaitem',
            name='grupo_agregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_tarefa', to='produtos.grupoagregado', verbose_name='grupo agregado'),
        ),
        migrations.RunPython(_vincular_grupo_agregado_nos_itens, migrations.RunPython.noop),
    ]
