# Generated by Django 6.0.4 on 2026-04-24 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0002_initial'),
        ('nf', '0002_remove_notafiscal_nf_chave_idx'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciaitem',
            name='observacao_divergencia',
            field=models.TextField(blank=True, null=True, verbose_name='observacao da divergencia'),
        ),
        migrations.AlterField(
            model_name='conferenciaitem',
            name='motivo_divergencia',
            field=models.CharField(blank=True, choices=[('FALTA', 'Falta'), ('EXCESSO', 'Excesso'), ('PRODUTO_ERRADO', 'Produto errado'), ('AVARIA', 'Avaria'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='motivo da divergencia'),
        ),
        migrations.AddIndex(
            model_name='conferenciaitem',
            index=models.Index(fields=['motivo_divergencia'], name='conf_item_motivo_idx'),
        ),
        migrations.AddConstraint(
            model_name='conferencia',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'EM_CONFERENCIA')), fields=('nf',), name='conferencia_nf_em_andamento_unique'),
        ),
        migrations.AddConstraint(
            model_name='conferenciaitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'DIVERGENCIA'), _negated=True), models.Q(('motivo_divergencia__isnull', False), models.Q(('motivo_divergencia', ''), _negated=True)), _connector='OR'), name='conf_item_motivo_divergencia_required_chk'),
        ),
    ]
