# Generated by Django 6.0.4 on 2026-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuariosessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuarios.setorusuario', verbose_name='setores'),
        ),
    ]
