# Generated by Django 6.0.4 on 2026-04-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_popular_setores_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetorUsuario',
            new_name='Setor',
        ),
    ]
