# Generated by Django 6.0.4 on 2026-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_garantir_setores_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ultima atividade'),
        ),
    ]
