# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_liberacaodivergencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='liberacaodivergencia',
            name='nf_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numero da nf'),
        ),
    ]
