# Generated by Django 6.0.4 on 2026-04-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notafiscal',
            name='nf_chave_idx',
        ),
    ]
