# Generated by Django 6.0.4 on 2026-04-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cliente_ie_idx'),
        ('nf', '0002_remove_notafiscal_nf_chave_idx'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BLOQUEADA_COM_RESTRICAO', 'Bloqueada com restricao'), ('LIBERADA_COM_RESTRICAO', 'Liberada com restricao')], db_index=True, default='NORMAL', max_length=30, verbose_name='status operacional'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status'], name='nf_status_operacional_idx'),
        ),
    ]
