# Generated by Django 6.0.4 on 2026-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cliente_ie_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rota',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='rota'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo'], name='cliente_codigo_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['rota'], name='cliente_rota_idx'),
        ),
    ]
