# Generated by Django 6.0.4 on 2026-05-25 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0007_enterprise_codigo_lookup'),
        ('recebimento', '0001_initial_estoque_temporario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo_posicao', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='cód. posição')),
                ('rua', models.CharField(max_length=30, verbose_name='rua')),
                ('posicao', models.CharField(max_length=30, verbose_name='posição')),
                ('andar', models.CharField(max_length=30, verbose_name='andar')),
                ('lado', models.CharField(max_length=30, verbose_name='lado')),
                ('setor', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='setor')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('BLOQUEADA', 'Bloqueada'), ('MANUTENCAO', 'Manutenção'), ('INVENTARIO', 'Inventário')], db_index=True, default='ATIVA', max_length=12, verbose_name='status')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='observação')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'posição de estoque',
                'verbose_name_plural': 'posições de estoque',
                'ordering': ('rua', 'posicao', 'andar', 'lado'),
                'indexes': [models.Index(fields=['status', 'ativo'], name='pos_est_status_ativo_ix'), models.Index(fields=['rua', 'posicao', 'andar', 'lado'], name='pos_est_endereco_ix')],
            },
        ),
        migrations.CreateModel(
            name='EstoqueFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo_produto', models.CharField(db_index=True, max_length=50, verbose_name='código produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade')),
                ('fifo_nf', models.CharField(db_index=True, max_length=32, verbose_name='FIFO')),
                ('data_entrada', models.DateTimeField(db_index=True, verbose_name='data entrada')),
                ('nf_entrada', models.CharField(db_index=True, max_length=20, verbose_name='NF entrada')),
                ('chave_nfe', models.CharField(blank=True, default='', max_length=44, verbose_name='chave NFe')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado')], db_index=True, default='ATIVO', max_length=12, verbose_name='status')),
                ('estoque_temporario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoques_fisicos', to='recebimento.estoquetemporario', verbose_name='origem TEMP')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estoques_fisicos', to='produtos.produto', verbose_name='produto')),
                ('usuario_armazenagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armazenagens_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='usuário armazenagem')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='estoque.posicaoestoque', verbose_name='posição')),
            ],
            options={
                'verbose_name': 'estoque físico',
                'verbose_name_plural': 'estoques físicos',
                'ordering': ('data_entrada', 'nf_entrada', 'codigo_produto'),
                'indexes': [models.Index(fields=['codigo_produto', 'data_entrada'], name='est_fis_prod_data_ix'), models.Index(fields=['fifo_nf'], name='est_fis_fifo_ix'), models.Index(fields=['posicao', 'status'], name='est_fis_pos_status_ix'), models.Index(fields=['status', 'quantidade'], name='est_fis_status_qtd_ix')],
            },
        ),
    ]
