# Generated by Django 6.0.4 on 2026-05-25 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial_estoque_enderecado'),
        ('produtos', '0007_enterprise_codigo_lookup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('REABASTECIMENTO', 'Reabastecimento'), ('AJUSTE', 'Ajuste'), ('BLOQUEIO', 'Bloqueio'), ('DESBLOQUEIO', 'Desbloqueio'), ('ARMAZENAGEM', 'Armazenagem')], db_index=True, max_length=20, verbose_name='tipo')),
                ('codigo_produto', models.CharField(db_index=True, max_length=50, verbose_name='código produto')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade')),
                ('fifo_nf', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='FIFO')),
                ('nf_entrada', models.CharField(blank=True, default='', max_length=20, verbose_name='NF entrada')),
                ('motivo', models.CharField(blank=True, default='', max_length=24, verbose_name='motivo')),
                ('observacao', models.CharField(blank=True, default='', max_length=255, verbose_name='observação')),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado')], db_index=True, default='CONFIRMADO', max_length=12, verbose_name='status')),
                ('estoque_fisico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.estoquefisico', verbose_name='linha estoque')),
                ('posicao_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_destino', to='estoque.posicaoestoque', verbose_name='posição destino')),
                ('posicao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_origem', to='estoque.posicaoestoque', verbose_name='posição origem')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='produtos.produto', verbose_name='produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['codigo_produto', 'created_at'], name='mov_est_prod_data_ix'), models.Index(fields=['fifo_nf', 'created_at'], name='mov_est_fifo_data_ix'), models.Index(fields=['tipo', 'created_at'], name='mov_est_tipo_data_ix'), models.Index(fields=['posicao_origem', 'created_at'], name='mov_est_orig_data_ix'), models.Index(fields=['posicao_destino', 'created_at'], name='mov_est_dest_data_ix'), models.Index(fields=['status', 'created_at'], name='mov_est_status_data_ix')],
            },
        ),
    ]
