# Generated by Django 6.0.4 on 2026-04-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_setor_novos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('CONCLUIDO', 'Concluido'), ('FECHADO_COM_RESTRICAO', 'Fechado com restricao'), ('LIBERADO_COM_RESTRICAO', 'Liberado com restricao')], db_index=True, max_length=30, verbose_name='status'),
        ),
    ]
