# Generated by Django 6.0.4 on 2026-04-25 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf', '0003_notafiscal_status_and_more'),
        ('produtos', '0001_initial'),
        ('tarefas', '0004_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tarefaitem',
            name='tarefa_item_unique_produto',
        ),
        migrations.RemoveIndex(
            model_name='tarefaitem',
            name='tarefa_item_tarefa_prod_idx',
        ),
        migrations.AddField(
            model_name='tarefaitem',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_tarefa', to='nf.notafiscal', verbose_name='nota fiscal'),
        ),
        migrations.AddField(
            model_name='tarefaitem',
            name='possui_restricao',
            field=models.BooleanField(default=False, verbose_name='possui restricao'),
        ),
        migrations.AddIndex(
            model_name='tarefaitem',
            index=models.Index(fields=['tarefa', 'produto', 'nf'], name='tarefa_item_tarefa_prod_nf_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefaitem',
            index=models.Index(fields=['nf', 'possui_restricao'], name='tarefa_item_nf_restricao_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarefaitem',
            constraint=models.UniqueConstraint(fields=('tarefa', 'produto', 'nf'), name='tarefa_item_unique_produto_nf'),
        ),
    ]
