# Generated by Django 6.0.4 on 2026-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('cod_prod', models.CharField(max_length=50, unique=True, verbose_name='codigo do produto')),
                ('descricao', models.CharField(db_index=True, max_length=255, verbose_name='descricao')),
                ('cod_ean', models.CharField(db_index=True, max_length=50, verbose_name='codigo EAN')),
                ('categoria', models.CharField(choices=[('LUBRIFICANTE', 'Lubrificante'), ('AGREGADO', 'Agregado'), ('FILTROS', 'Filtros'), ('NAO_ENCONTRADO', 'Nao encontrado')], max_length=20, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ('cod_prod',),
                'indexes': [models.Index(fields=['cod_prod'], name='produto_cod_prod_idx'), models.Index(fields=['cod_ean'], name='produto_cod_ean_idx'), models.Index(fields=['categoria'], name='produto_categoria_idx')],
            },
        ),
    ]
