# Generated by Django 6.0.4 on 2026-04-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_cadastrado_manual_produto_incompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='codigo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='embalagem',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='embalagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='setor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='setor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cod_ean',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='codigo EAN'),
        ),
    ]
