# Generated by Django 6.0.4 on 2026-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_grupoagregado_produto_grupos_agregados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='setor',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='setor'),
        ),
    ]