# Generated by Django 6.0.4 on 2026-05-25 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueTemporario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('chave_nfe', models.CharField(db_index=True, max_length=44, verbose_name='chave NFe')),
                ('nf_numero', models.CharField(db_index=True, max_length=20, verbose_name='número NF')),
                ('produto_codigo', models.CharField(db_index=True, max_length=50, verbose_name='código produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data recebimento')),
                ('canal', models.CharField(choices=[('TEMP', 'TEMP')], db_index=True, default='TEMP', max_length=10, verbose_name='canal')),
                ('xml_origem', models.CharField(blank=True, default='', max_length=255, verbose_name='origem XML')),
                ('status', models.CharField(choices=[('TEMP', 'Temporário'), ('VALIDADO', 'Validado'), ('RESGATADO', 'Resgatado'), ('CANCELADO', 'Cancelado')], db_index=True, default='TEMP', max_length=12, verbose_name='status')),
                ('tp_nf', models.CharField(blank=True, default='', max_length=1, verbose_name='tpNF')),
                ('nat_op', models.CharField(blank=True, default='', max_length=120, verbose_name='natOp')),
                ('emitente_cnpj', models.CharField(blank=True, default='', max_length=14, verbose_name='CNPJ emitente')),
                ('destinatario_cnpj', models.CharField(blank=True, default='', max_length=14, verbose_name='CNPJ destinatário')),
                ('usuario_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques_temporarios_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='usuário recebimento')),
            ],
            options={
                'verbose_name': 'estoque temporário',
                'verbose_name_plural': 'estoques temporários',
                'ordering': ('-data_recebimento', 'nf_numero', 'produto_codigo'),
                'indexes': [models.Index(fields=['status', 'data_recebimento'], name='est_temp_status_data_ix'), models.Index(fields=['nf_numero', 'produto_codigo'], name='est_temp_nf_prod_ix')],
            },
        ),
    ]
