# Generated by Django 6.0.4 on 2026-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('perfil', models.CharField(choices=[('SEPARADOR', 'Separador'), ('CONFERENTE', 'Conferente'), ('GESTOR', 'Gestor')], max_length=20, verbose_name='perfil')),
                ('setor', models.CharField(choices=[('LUBRIFICANTE', 'Lubrificante'), ('AGREGADO', 'Agregado'), ('FILTROS', 'Filtros'), ('NAO_ENCONTRADO', 'Nao encontrado')], max_length=20, verbose_name='setor')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['username'], name='usuario_username_idx'), models.Index(fields=['perfil', 'setor'], name='usuario_perf_set_idx'), models.Index(fields=['is_active'], name='usuario_active_idx')],
            },
        ),
    ]
