# Generated by Django 6.0.4 on 2026-04-24 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['usuario', 'created_at'], name='log_usuario_created_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['acao'], name='log_acao_idx'),
        ),
    ]
