# Generated by Django 6.0.4 on 2026-04-25 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        ('nf', '0002_remove_notafiscal_nf_chave_idx'),
        ('tarefas', '0004_alter_tarefa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoDivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('status_anterior', models.CharField(max_length=40, verbose_name='status anterior')),
                ('status_novo', models.CharField(max_length=40, verbose_name='status novo')),
                ('nf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_divergencia', to='nf.notafiscal', verbose_name='nota fiscal')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_divergencia', to='tarefas.tarefa', verbose_name='tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_divergencia', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'liberacao de divergencia',
                'verbose_name_plural': 'liberacoes de divergencia',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='lib_div_created_idx'), models.Index(fields=['usuario', 'created_at'], name='lib_div_user_created_idx'), models.Index(fields=['status_anterior', 'status_novo'], name='lib_div_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nf__isnull', False), ('tarefa__isnull', False), _connector='OR'), name='lib_div_nf_or_tarefa_required_chk')],
            },
        ),
    ]
