# Generated by Django 6.0.4 on 2026-04-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_tarefa_usuario_execucao_data_inicio'),
        ('logs', '0004_liberacaodivergencia_nf_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('bipagem', 'Bipagem'), ('tarefa_inicio', 'Tarefa inicio'), ('tarefa_fim', 'Tarefa fim')], db_index=True, max_length=20, verbose_name='tipo')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tarefas.tarefa', verbose_name='tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'user activity log',
                'verbose_name_plural': 'user activity logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='ual_user_ts_idx'), models.Index(fields=['tipo', 'timestamp'], name='ual_tipo_ts_idx'), models.Index(fields=['tarefa', 'timestamp'], name='ual_tarefa_ts_idx')],
            },
        ),
    ]
