# Generated by Django 6.0.4 on 2026-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_CONFERENCIA', 'Em conferencia'), ('OK', 'OK'), ('DIVERGENCIA', 'Divergencia'), ('CANCELADA', 'Cancelada')], db_index=True, max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'conferencia',
                'verbose_name_plural': 'conferencias',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('qtd_esperada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade esperada')),
                ('qtd_conferida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='quantidade conferida')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('OK', 'OK'), ('DIVERGENCIA', 'Divergencia'), ('CANCELADA', 'Cancelada')], db_index=True, max_length=20, verbose_name='status')),
                ('motivo_divergencia', models.TextField(blank=True, null=True, verbose_name='motivo da divergencia')),
            ],
            options={
                'verbose_name': 'item da conferencia',
                'verbose_name_plural': 'itens da conferencia',
                'ordering': ('conferencia_id', 'produto_id'),
            },
        ),
    ]
