# Generated by Django 6.0.4 on 2026-04-24 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferencia', '0001_initial'),
        ('nf', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='conferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencias', to=settings.AUTH_USER_MODEL, verbose_name='conferente'),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='nf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='nf.notafiscal', verbose_name='nota fiscal'),
        ),
        migrations.AddField(
            model_name='conferenciaitem',
            name='conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='conferencia.conferencia', verbose_name='conferencia'),
        ),
        migrations.AddField(
            model_name='conferenciaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_conferencia', to='produtos.produto', verbose_name='produto'),
        ),
        migrations.AddIndex(
            model_name='conferencia',
            index=models.Index(fields=['nf', 'status'], name='conf_nf_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conferencia',
            index=models.Index(fields=['conferente', 'status'], name='conf_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenciaitem',
            index=models.Index(fields=['conferencia', 'produto'], name='conf_item_conf_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenciaitem',
            index=models.Index(fields=['status'], name='conf_item_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='conferenciaitem',
            constraint=models.UniqueConstraint(fields=('conferencia', 'produto'), name='conf_item_unique_produto'),
        ),
        migrations.AddConstraint(
            model_name='conferenciaitem',
            constraint=models.CheckConstraint(condition=models.Q(('qtd_esperada__gte', 0), ('qtd_conferida__gte', 0)), name='conf_item_quantidades_validas_chk'),
        ),
    ]
