# Generated by Django 6.0.4 on 2026-04-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0003_conferenciaitem_observacao_divergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_CONFERENCIA', 'Em conferencia'), ('OK', 'OK'), ('DIVERGENCIA', 'Divergencia'), ('LIBERADO_COM_RESTRICAO', 'Liberado com restricao'), ('CANCELADA', 'Cancelada')], db_index=True, max_length=30, verbose_name='status'),
        ),
    ]
