# Generated by Django 6.0.4 on 2026-04-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('chave_nfe', models.CharField(db_index=True, max_length=44, unique=True, verbose_name='chave NFe')),
                ('numero', models.CharField(db_index=True, max_length=20, verbose_name='numero')),
                ('data_emissao', models.DateTimeField(db_index=True, verbose_name='data de emissao')),
                ('status_fiscal', models.CharField(choices=[('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada')], max_length=20, verbose_name='status fiscal')),
                ('bloqueada', models.BooleanField(default=False, verbose_name='bloqueada')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='clientes.cliente', verbose_name='cliente')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='rotas.rota', verbose_name='rota')),
            ],
            options={
                'verbose_name': 'nota fiscal',
                'verbose_name_plural': 'notas fiscais',
                'ordering': ('-data_emissao', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='quantidade')),
                ('nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='nf.notafiscal', verbose_name='nota fiscal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nota_fiscal', to='produtos.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item da nota fiscal',
                'verbose_name_plural': 'itens da nota fiscal',
                'ordering': ('nf_id', 'produto_id'),
            },
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['chave_nfe'], name='nf_chave_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['numero'], name='nf_numero_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status_fiscal', 'ativa'], name='nf_status_ativa_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['cliente', 'rota'], name='nf_cliente_rota_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['nf', 'produto'], name='nf_item_nf_prod_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscalitem',
            index=models.Index(fields=['produto'], name='nf_item_produto_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscalitem',
            constraint=models.UniqueConstraint(fields=('nf', 'produto'), name='nf_item_unique_produto'),
        ),
    ]
