# Generated by Django 6.0.4 on 2026-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='cep_final_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='CEP final numerico'),
        ),
        migrations.AddField(
            model_name='rota',
            name='cep_inicial_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='CEP inicial numerico'),
        ),
        migrations.AddField(
            model_name='rota',
            name='nome_rota',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='nome da rota'),
        ),
        migrations.AddField(
            model_name='rota',
            name='praca',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='praca'),
        ),
        migrations.AddIndex(
            model_name='rota',
            index=models.Index(fields=['praca'], name='rota_praca_idx'),
        ),
        migrations.AddIndex(
            model_name='rota',
            index=models.Index(fields=['nome_rota'], name='rota_nome_rota_idx'),
        ),
        migrations.AddIndex(
            model_name='rota',
            index=models.Index(fields=['cep_inicial_num', 'cep_final_num'], name='rota_cep_faixa_num_idx'),
        ),
    ]
