# Generated by Django 6.0.4 on 2026-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('cep_inicial', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP inicial')),
                ('cep_final', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP final')),
                ('bairro', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='bairro')),
            ],
            options={
                'verbose_name': 'rota',
                'verbose_name_plural': 'rotas',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['nome'], name='rota_nome_idx'), models.Index(fields=['bairro'], name='rota_bairro_idx'), models.Index(fields=['cep_inicial', 'cep_final'], name='rota_cep_faixa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cep_inicial__isnull', False), models.Q(('cep_inicial', ''), _negated=True), ('cep_final__isnull', False), models.Q(('cep_final', ''), _negated=True), ('bairro__isnull', True)), models.Q(('cep_inicial__isnull', True), ('cep_final__isnull', True), ('bairro__isnull', False), models.Q(('bairro', ''), _negated=True)), _connector='OR'), name='rota_cep_ou_bairro_chk')],
            },
        ),
    ]
