# Generated by Django 6.0.4 on 2026-04-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('inscricao_estadual', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='inscricao estadual')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['nome'], name='cliente_nome_idx'), models.Index(fields=['inscricao_estadual'], name='cliente_ie_idx')],
            },
        ),
    ]
